# Generated by Django 5.1.7 on 2025-03-26 20:49

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='Male', max_length=10)),
                ('degree', models.CharField(choices=[('Bachelor', 'Бакалавр'), ('Master', 'Магистр'), ('PhD', 'Доктор философии')], default='Bachelor', max_length=10)),
                ('position', models.CharField(choices=[('Junior Librarian', 'Младший библиотекарь'), ('Librarian', 'Библиотекарь'), ('Senior Librarian', 'Старший библиотекарь'), ('Library Manager', 'Менеджер библиотеки'), ('Director', 'Директор')], default='Junior Librarian', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_hire', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('library_branch', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
