# Generated by Django 5.1.7 on 2025-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_hire',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='library_branch',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес проживание '),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'Бакалавр'), ('Master', 'Магистр'), ('PhD', 'Доктор философии')], default='Bachelor', max_length=10, verbose_name='Образования'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Диплом'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='нет пола', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Junior Librarian', 'Младший библиотекарь'), ('Librarian', 'Библиотекарь'), ('Senior Librarian', 'Старший библиотекарь'), ('Library Manager', 'Менеджер библиотеки'), ('Director', 'Директор')], default='Junior Librarian', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата'),
        ),
    ]
