# Generated by Django 5.1.7 on 2025-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_date_of_hire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Магистр', 'Магистр'), ('Аспирантура', 'Аспирантура')], default='Bachelor', max_length=20, verbose_name='Образования'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Младший библиотекарь', 'Младший библиотекарь'), ('Библиотекарь', 'Библиотекарь'), ('Старший библиотекарь', 'Старший библиотекарь'), ('Менеджер библиотеки', 'Менеджер библиотеки'), ('Директор', 'Директор')], default='Junior Librarian', max_length=100, verbose_name='Должность'),
        ),
    ]
