# Generated by Django 5.1.7 on 2025-03-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Детектив', 'Детектив'), ('Мистика', 'Мистика')], max_length=10)),
                ('author_email', models.EmailField(default=0, max_length=254)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book/')),
                ('video_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('👍', '👍'), ('👍👍', '👍👍'), ('👍👍👍', '👍👍👍'), ('👍👍👍👍', '👍👍👍👍'), ('👍👍👍👍👍', '👍👍👍👍👍')], default='👍', max_length=10)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
            ],
        ),
    ]
