# Generated by Django 5.1.7 on 2025-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Детектив', 'Детектив'), ('Мистика', 'Мистика')], max_length=10)),
                ('author_email', models.EmailField(max_length=254)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='books/')),
                ('video_url', models.URLField()),
            ],
        ),
    ]
