# Generated by Django 5.1.7 on 2025-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
