# Generated by Django 5.1.7 on 2025-03-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.AddField(
            model_name='book',
            name='author_email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='book',
            name='video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Детектив', 'Детектив'), ('Мистика', 'Мистика')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='book/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('👍', '👍'), ('👍👍', '👍👍'), ('👍👍👍', '👍👍👍'), ('👍👍👍👍', '👍👍👍👍'), ('👍👍👍👍👍', '👍👍👍👍👍')], default='👍', max_length=10)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
