# Generated by Django 5.1.7 on 2025-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comments_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('children', 'children'), ('teen', 'teen')], default=0, max_length=50),
        ),
    ]
