# Generated by Django 5.1.7 on 2025-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='grade',
            field=models.CharField(choices=[('👍', '👍'), ('👍👍', '👍👍'), ('👍👍👍', '👍👍👍'), ('👍👍👍👍', '👍👍👍👍'), ('👍👍👍👍👍', '👍👍👍👍👍')], default='👍', max_length=10),
        ),
    ]
