# Generated by Django 5.1.7 on 2025-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_comments_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('children', 'children'), ('teen', 'teen')], default='teen', max_length=50),
        ),
    ]
