# Generated by Django 5.1.7 on 2025-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_remove_mangamodel_title_mangamodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangamodel',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
