# Generated by Django 5.1.7 on 2025-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_mangamodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezkaFilmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
