# Generated by Django 5.1.7 on 2025-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_rezkafilmsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezkafilmsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
