# Generated by Django 5.1.7 on 2025-03-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_post_title_alter_tag_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
